import { useState } from 'react';
import { PrimaryButton } from '../components/ui.jsx';

function relativeTime(iso) {
  if (!iso) return '';
  const diffMs = Date.now() - new Date(iso).getTime();
  const mins = Math.round(diffMs / 60000);
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.round(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.round(hours / 24)}d ago`;
}

function FileTree({ tree, depth = 0 }) {
  if (!tree) return null;
  const folders = Object.keys(tree).filter((k) => k !== '__files');
  const files = tree.__files || [];
  return (
    <div>
      {folders.map((folder) => (
        <div key={folder}>
          <div style={{ padding: `4px 16px 4px ${16 + depth * 16}px`, display: 'flex', alignItems: 'center', gap: 8 }}>
            <span style={{ color: 'var(--blue)', fontSize: 10 }}>▸</span>
            <span style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 12, color: 'var(--muted)' }}>{folder}</span>
          </div>
          <FileTree tree={tree[folder]} depth={depth + 1} />
        </div>
      ))}
      {files.map((f) => (
        <div key={f} style={{ padding: `4px 16px 4px ${32 + depth * 16}px`, display: 'flex', alignItems: 'center', gap: 8 }}>
          <span style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 12, color: 'var(--text)' }}>{f}</span>
        </div>
      ))}
    </div>
  );
}

function buildTreeText(tree, depth = 0) {
  if (!tree) return '';
  let out = '';
  const folders = Object.keys(tree).filter((k) => k !== '__files');
  const files = tree.__files || [];
  for (const folder of folders) {
    out += `${'  '.repeat(depth)}${folder}/\n`;
    out += buildTreeText(tree[folder], depth + 1);
  }
  for (const f of files) {
    out += `${'  '.repeat(depth)}${f}\n`;
  }
  return out;
}

function buildResumeMarkdown(repo, sessionNote) {
  const treeText = buildTreeText(repo.fileTree);
  const commitsText = (repo.recentCommits || [])
    .map((c) => `- ${c.message} (${c.author}, ${relativeTime(c.date)})`)
    .join('\n') || '- No recent commit history available.';
  const keyFilesText = (repo.keyFiles || [])
    .map((f) => `### ${f.path}\n\n\`\`\`\n${f.preview}\n\`\`\``)
    .join('\n\n');

  return `# ${repo.fullName} — Codebase Context

> Generated by GetContext. This file captures both the codebase structure AND what was being worked on, so a new AI agent session can resume where the last one left off — paste or upload this as your first message.

## Overview
${repo.description || 'No description available.'}

**Tech stack:** ${(repo.technologies || []).join(', ') || 'Unknown'}
**Files indexed:** ${repo.fileCount}

## Recent activity
${commitsText}

## Current task
${sessionNote ? sessionNote : 'No session note provided — resume by reviewing recent activity and key files below.'}

## Folder structure
\`\`\`
${treeText}\`\`\`

## Key files

${keyFilesText}
`;
}

function downloadMarkdown(filename, content) {
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export default function RepoDashboard({ repo, onGoExplorer }) {
  const [treeOpen, setTreeOpen] = useState(true);
  const [sessionNote, setSessionNote] = useState('');

  if (!repo) return null;

  function handleResume() {
    const md = buildResumeMarkdown(repo, sessionNote);
    const filename = `${repo.fullName.replace(/\//g, '-')}-context.md`;
    downloadMarkdown(filename, md);
  }

  return (
    <div style={{ maxWidth: 1200, margin: '0 auto', padding: '40px 24px' }}>
      {/* Breadcrumb Path */}
      <div style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 12, color: 'var(--muted)', marginBottom: 24, display: 'flex', alignItems: 'center', gap: 8 }}>
        <span style={{ color: 'var(--accent-light)' }}>~/repos</span>
        <span>/</span>
        <span style={{ color: '#FFFFFF', fontWeight: 600 }}>{repo.fullName}</span>
      </div>

      {repo.degraded && (
        <div style={{ fontFamily: 'Inter, sans-serif', fontSize: 13, color: 'var(--accent-light)', border: '1px solid rgba(99,102,241,0.3)', backgroundColor: 'rgba(99,102,241,0.08)', borderRadius: 12, padding: '12px 16px', marginBottom: 24 }}>
          ℹ {repo.message || 'Live GitHub fetch was unavailable — showing the bundled demo repository instead.'}
        </div>
      )}

      {/* Header Info Banner */}
      <div style={{ marginBottom: 32, display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 24, flexWrap: 'wrap' }}>
        <div>
          <h1 style={{ fontFamily: 'Inter, sans-serif', fontWeight: 700, fontSize: 30, color: '#FFFFFF', margin: '0 0 10px', letterSpacing: '-0.03em' }}>
            {repo.fullName}
          </h1>
          <p style={{ fontFamily: 'Inter, sans-serif', fontSize: 15, color: 'var(--muted)', margin: '0 0 16px', maxWidth: 580, lineHeight: 1.6 }}>
            {repo.description || 'No description available.'}
          </p>
          <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
            {(repo.technologies || []).map((t) => (
              <span key={t} style={{
                fontFamily: 'JetBrains Mono, monospace',
                fontSize: 11,
                color: '#A5B4FC',
                border: '1px solid rgba(99,102,241,0.25)',
                padding: '4px 10px',
                borderRadius: 8,
                backgroundColor: 'rgba(99,102,241,0.08)'
              }}>{t}</span>
            ))}
          </div>
        </div>

        {/* Stats Row */}
        <div style={{ display: 'flex', gap: 24, flexShrink: 0 }}>
          {[
            { label: 'files', value: repo.fileCount },
            { label: 'indexed', value: repo.fetchedFileCount },
            { label: 'tokens', value: repo.repositoryTokens?.toLocaleString() },
          ].map((s) => (
            <div key={s.label} style={{
              textAlign: 'center',
              backgroundColor: 'rgba(18, 21, 30, 0.7)',
              border: '1px solid rgba(255, 255, 255, 0.08)',
              borderRadius: 14,
              padding: '14px 20px',
              minWidth: 90
            }}>
              <div style={{ fontFamily: 'JetBrains Mono, monospace', fontWeight: 700, fontSize: 22, color: '#FFFFFF' }}>{s.value}</div>
              <div style={{ fontFamily: 'Inter, sans-serif', fontSize: 12, color: 'var(--muted)', marginTop: 2 }}>{s.label}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Grid: File Tree & Recent Activity */}
      <div data-grid-two style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)', gap: 20, marginBottom: 20 }}>
        
        {/* File Tree Card */}
        <div style={{
          backgroundColor: 'rgba(18, 21, 30, 0.85)',
          border: '1px solid rgba(255, 255, 255, 0.08)',
          borderRadius: 16,
          overflow: 'hidden'
        }}>
          <button
            onClick={() => setTreeOpen((v) => !v)}
            style={{ width: '100%', backgroundColor: 'transparent', border: 'none', borderBottom: '1px solid rgba(255, 255, 255, 0.08)', padding: '14px 20px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', cursor: 'pointer' }}
          >
            <span style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 12, color: '#A5B4FC', fontWeight: 600, display: 'flex', alignItems: 'center', gap: 8 }}>
              <span style={{ color: 'var(--accent)' }}>▸</span> FILE TREE
            </span>
            <span style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 11, color: 'var(--muted)' }}>{treeOpen ? '▲ collapse' : '▼ expand'}</span>
          </button>
          {treeOpen && <div style={{ padding: '12px 8px', maxHeight: 300, overflowY: 'auto' }}><FileTree tree={repo.fileTree} /></div>}
        </div>

        {/* Recent Activity Card */}
        <div style={{
          backgroundColor: 'rgba(18, 21, 30, 0.85)',
          border: '1px solid rgba(255, 255, 255, 0.08)',
          borderRadius: 16,
          overflow: 'hidden'
        }}>
          <div style={{ borderBottom: '1px solid rgba(255, 255, 255, 0.08)', padding: '14px 20px' }}>
            <span style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 12, color: '#A5B4FC', fontWeight: 600, display: 'flex', alignItems: 'center', gap: 8 }}>
              <span style={{ color: 'var(--success)' }}>●</span> RECENT ACTIVITY
            </span>
          </div>
          <div style={{ maxHeight: 300, overflowY: 'auto' }}>
            {(repo.recentCommits || []).length === 0 && (
              <div style={{ padding: 20, fontFamily: 'Inter, sans-serif', fontSize: 13, color: 'var(--muted)' }}>No commit history available.</div>
            )}
            {(repo.recentCommits || []).map((c, i) => (
              <div key={i} style={{ padding: '14px 20px', borderBottom: '1px solid rgba(255, 255, 255, 0.05)' }}>
                <div style={{ fontFamily: 'Inter, sans-serif', fontSize: 14, color: '#FFFFFF', marginBottom: 4, lineHeight: 1.4 }}>{c.message}</div>
                <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                  <span style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 11, color: 'var(--accent-light)' }}>@{c.author}</span>
                  <span style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 11, color: 'var(--muted)', marginLeft: 'auto' }}>{relativeTime(c.date)}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Working Session Note */}
      <div style={{
        backgroundColor: 'rgba(18, 21, 30, 0.85)',
        border: '1px solid rgba(255, 255, 255, 0.08)',
        borderRadius: 18,
        padding: 28,
        marginBottom: 20
      }}>
        <label style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 12, color: '#A5B4FC', display: 'block', marginBottom: 12, fontWeight: 600 }}>
          // WHAT WERE YOU WORKING ON? (optional — appended to context)
        </label>
        <textarea
          value={sessionNote}
          onChange={(e) => setSessionNote(e.target.value)}
          placeholder="e.g. debugging the auth redirect loop, fix is half-done in authMiddleware.js…"
          rows={4}
          style={{
            width: '100%',
            backgroundColor: '#090A0F',
            border: '1px solid rgba(255, 255, 255, 0.1)',
            borderRadius: 12,
            color: '#FFFFFF',
            fontFamily: 'JetBrains Mono, monospace',
            fontSize: 13,
            padding: '14px 16px',
            resize: 'vertical',
            outline: 'none',
            lineHeight: 1.7,
            boxSizing: 'border-box'
          }}
        />
        <div style={{ marginTop: 20, display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: 14, flexWrap: 'wrap' }}>
          <PrimaryButton onClick={handleResume} style={{ backgroundColor: 'rgba(99, 102, 241, 0.2)', color: '#A5B4FC', border: '1px solid rgba(99,102,241,0.4)', boxShadow: 'none' }}>
            Resume in New Agent (download) ↓
          </PrimaryButton>
          <PrimaryButton onClick={onGoExplorer}>
            Ask a question →
          </PrimaryButton>
        </div>
      </div>
    </div>
  );
}

